import tkinter as tk
window= tk.Tk()
window.title =("WIndow shtt")
window.configure(bg="purple")
window.resizable(False,True)
window.geometry("600x600")
label = tk.Label(window,text="Student Profile",font=("arial",20,"bold"),bg="purple",fg="black",height=2,width=10,anchor="center")
studentname = tk.Label(window,text="Name:Kurt Dashiel Pacaigue",font=("arial",13),bg="purple",fg="black",width=10,height=2,anchor="w")
studentage = tk.Label(window,text="Age:23 years old",font=("arial",13),bg="purple",fg="black",width=10,height=2,anchor="w")
studentcourse = tk.Label(window,text="Course: BSIT",font=("arial",13),bg="purple",fg="black",width=10,height=2,anchor="w")
studentbirthday = tk.Label(window,text="Birthday:November 5,2006",font=("arial",13),bg="purple",fg="black",width=10,height=2,anchor="w")
studentmotto = tk.Label(window,text="Motto:",font=("arial",13),bg="purple",fg="black",width=10,height=2,anchor="w")
studentmotto1 = tk.Label(window,text="I Always Come Back",font=("arial",13),bg="purple",fg="black",width=10,height=2,anchor="center")

label.pack(padx=10,pady=5,fill="x",expand=False)
studentname.pack(padx=10,pady=5,fill="x")
studentage.pack(padx=10,pady=5,fill="x")
studentcourse.pack(padx=10,pady=5,fill="x")
studentbirthday.pack(padx=10,pady=5,fill="x")
studentmotto.pack(padx=10,pady=5,fill="x")
studentmotto1.pack(padx=10,pady=5,fill="x")

window.mainloop()
